# Extra config for debugging
#CONFIG_SHELL=y
#CONFIG_I2C_SHELL=y
#CONFIG_I2C_LOG_LEVEL_DBG=y
#CONFIG_I2C_DUMP_MESSAGES=y

# https://www.reddit.com/r/embedded/comments/1508qbj/lvgl_ssd1306_and_zephyr/
CONFIG_LV_COLOR_DEPTH_1=y
CONFIG_LV_Z_BITS_PER_PIXEL=1
CONFIG_LV_Z_VDB_SIZE=100
CONFIG_LV_DPI_DEF=149

CONFIG_LV_Z_FULL_REFRESH=y
CONFIG_LV_Z_BUFFER_ALLOC_STATIC=y
CONFIG_LV_Z_MONOCHROME_CONVERSION_BUFFER=y